# Server configuration
server:
  host: "0.0.0.0" # Host to bind the server to
  port: "8080" # Port to bind the server to

# Database configuration
db:
  type: "sqlite" # Database type (sqlite or postgres)
  host: "localhost" # Database host (for PostgreSQL)
  port: 5432 # Database port (for PostgreSQL)
  user: "postgres" # Database user (for PostgreSQL)
  password: "" # Database password (for PostgreSQL)
  database: "print-dis.db" # Database path (for SQLite) or name (for PostgreSQL)
  ssl_mode: "disable" # Database SSL mode (for PostgreSQL)

# Logging configuration
log:
  level: "info" # Log level (debug, info, warn, error)

# Spoolman integration configuration
spoolman:
  enabled: false # Enable Spoolman integration
  endpoint: "http://localhost:8000" # Spoolman API endpoint

# Auth configuration
auth:
  enabled: true
  session_secret: "change-me-in-production" # Change this in production!
  session_timeout: "24h"

  # Local authentication (username/password)
  local_auth:
    enabled: true
    allow_registration: false # Set to true to allow users to register themselves

  # OIDC (OAuth/OpenID Connect) providers
  oidc:
    google:
      client_id: ""
      client_secret: ""
      enabled: false
    microsoft:
      client_id: ""
      client_secret: ""
      enabled: false
