// Code generated by "enumer -type=PrintRequestStatus -json -text -output=print_request_status_gen.go"; DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PrintRequestStatusName = "StatusPendingApprovalStatusEnqueuedStatusInProgressStatusDone"

var _PrintRequestStatusIndex = [...]uint8{0, 21, 35, 51, 61}

const _PrintRequestStatusLowerName = "statuspendingapprovalstatusenqueuedstatusinprogressstatusdone"

func (i PrintRequestStatus) String() string {
	if i < 0 || i >= PrintRequestStatus(len(_PrintRequestStatusIndex)-1) {
		return fmt.Sprintf("PrintRequestStatus(%d)", i)
	}
	return _PrintRequestStatusName[_PrintRequestStatusIndex[i]:_PrintRequestStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PrintRequestStatusNoOp() {
	var x [1]struct{}
	_ = x[StatusPendingApproval-(0)]
	_ = x[StatusEnqueued-(1)]
	_ = x[StatusInProgress-(2)]
	_ = x[StatusDone-(3)]
}

var _PrintRequestStatusValues = []PrintRequestStatus{StatusPendingApproval, StatusEnqueued, StatusInProgress, StatusDone}

var _PrintRequestStatusNameToValueMap = map[string]PrintRequestStatus{
	_PrintRequestStatusName[0:21]:       StatusPendingApproval,
	_PrintRequestStatusLowerName[0:21]:  StatusPendingApproval,
	_PrintRequestStatusName[21:35]:      StatusEnqueued,
	_PrintRequestStatusLowerName[21:35]: StatusEnqueued,
	_PrintRequestStatusName[35:51]:      StatusInProgress,
	_PrintRequestStatusLowerName[35:51]: StatusInProgress,
	_PrintRequestStatusName[51:61]:      StatusDone,
	_PrintRequestStatusLowerName[51:61]: StatusDone,
}

var _PrintRequestStatusNames = []string{
	_PrintRequestStatusName[0:21],
	_PrintRequestStatusName[21:35],
	_PrintRequestStatusName[35:51],
	_PrintRequestStatusName[51:61],
}

// PrintRequestStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PrintRequestStatusString(s string) (PrintRequestStatus, error) {
	if val, ok := _PrintRequestStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PrintRequestStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PrintRequestStatus values", s)
}

// PrintRequestStatusValues returns all values of the enum
func PrintRequestStatusValues() []PrintRequestStatus {
	return _PrintRequestStatusValues
}

// PrintRequestStatusStrings returns a slice of all String values of the enum
func PrintRequestStatusStrings() []string {
	strs := make([]string, len(_PrintRequestStatusNames))
	copy(strs, _PrintRequestStatusNames)
	return strs
}

// IsAPrintRequestStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PrintRequestStatus) IsAPrintRequestStatus() bool {
	for _, v := range _PrintRequestStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PrintRequestStatus
func (i PrintRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PrintRequestStatus
func (i *PrintRequestStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PrintRequestStatus should be a string, got %s", data)
	}

	var err error
	*i, err = PrintRequestStatusString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for PrintRequestStatus
func (i PrintRequestStatus) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for PrintRequestStatus
func (i *PrintRequestStatus) UnmarshalText(text []byte) error {
	var err error
	*i, err = PrintRequestStatusString(string(text))
	return err
}
